### ISSUE TITLE
データベースにしまうデータの形式を決定する

### ISSUE THREAD

**Issue by mameccof** [mameccof/intern-introduction-quiz#14]
## 概要 (Summary):
データベースのフィールドに入る要素の形式をきめる
## 誰が使うか (For whom):
開発者
## 何のために or どのように実装するか (For what):
データを格納するときに必要なため　スプレッドシートにまとめる
## 達成目標:
各テーブルの要素が定まっている

対象のスプレッドシート
https://docs.google.com/spreadsheets/d/1uBS6SRCc96Lfq8s3N4D6cZrCzziDBT2mHGLXv_r5rwM/edit#gid=498822361

**Comment by hikaru-nakamura-thedott** [comment]
キャメルケースとスネークケースと色々混在しているので統一しましょ！

- コレクション名はキャメルケース
    - User, TemplateQuestion
- フィールド名
    - すべて小文字のスネークケース
    - セパレータは_を利用する
    - あとこれは、ドキュメント作成的な私的なんだけど、user_idは大事なフィールドだから一番上がいいな
    - user_id, birth_place, affilition
  
<img width="233" alt="スクリーンショット 2022-07-05 18 39 14" src="https://user-images.githubusercontent.com/86763776/177299288-25bf3339-d3dc-401d-990a-551ab90145be.png">

**Comment by hikaru-nakamura-thedott** [comment]
Usersにfollowingとfollowersというフィールドを追加してもらえますか？

今、strapiのリレーション周りを調べたらRelationフィールドの機能を調べたら、中間テーブル作らなくてもいいみたいです。
多対多の設定でRelationフィールド作るだけで内部的に中間テーブルが作られるみたいっす。

中間テーブルのシートは勉強のために残しておいて、strapiの使用に合わせてフィールド作成していきましょうか。
