### ISSUE TITLE
プロフィールを追加する

### ISSUE THREAD

**Issue by mameccof** [mameccof/intern-introduction-quiz#24]
## 概要 (Summary):
新規追加時にプロフィールを追加する
## 誰が使うか (For whom):
ユーザー
## 何のために or どのように実装するか (For what):
プロフィールを追加するためのAPIを叩く
## 達成目標:
新規追加から、項目を入力してデータベースに保存できる

**Comment by hikaru-nakamura-thedott** [comment]
https://github.com/mameccof/intern-introduction-quiz/issues/25 で実装するのでClose
