### ISSUE TITLE
問題のテンプレートを用意する

### ISSUE THREAD

**Issue by mameccof** [mameccof/intern-introduction-quiz#42]
## 概要 (Summary):
問題の内容を10問分考える
## 誰が使うか (For whom):
開発者
## 何のために or どのように実装するか (For what):
ユーザーが自分で問題を考えなくても問題追加ができるために
## 達成目標:
テンプレートになる問題を考える。
DBに登録まではしなくていい。
以下のスプレッドシートに保存
https://docs.google.com/spreadsheets/d/10_ISUiCMcZCnGFLgW2wGdbBvrESGSrZq4HkD9rVNDaE/edit#gid=0

**Comment by hikaru-nakamura-thedott** [comment]
10個作成したのが確認できたのでclose
