### ISSUE TITLE
ホーム画面に各画面への遷移するボタンを用意する

### ISSUE THREAD

**Issue by mameccof** [mameccof/intern-introduction-quiz#43]
## 概要 (Summary):
ホーム画面から各画面へ遷移できるようにする
## 誰が使うか (For whom):
ユーザー
## 何のために or どのように実装するか (For what):
各画面の機能を実装して、ホーム画面にまとめる
## 達成目標:
ホームから各画面へ移動できる

**Comment by hikaru-nakamura-thedott** [comment]
#13 で対応していた
